version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=postgres'
      - 'POSTGRESQL_PASSWORD=postgres'

volumes:
  postgresql_data:
    driver: local